/**
 * Step 4 — Reconstrução completa do currículo.
 *
 * Recebe: currículo original + diagnóstico step1 + avaliação GitHub step3.
 * Produz: JSON estruturado com todas as seções do currículo reconstruído.
 */
export function buildStep4Prompt({ resume, step1Result, step3Result }) {
  const diagnostico = JSON.stringify(step1Result, null, 2)
  const avaliacao = JSON.stringify(step3Result, null, 2)

  return [
    'Você é ResumeForge. Sua tarefa é RECONSTRUIR completamente o currículo abaixo,',
    'aplicando todas as melhorias identificadas na análise e incorporando os melhores projetos do GitHub.',
    '',
    'CURRÍCULO ORIGINAL:',
    '---',
    resume,
    '---',
    '',
    'DIAGNÓSTICO DA ANÁLISE (Step 1):',
    diagnostico,
    '',
    'AVALIAÇÃO DOS PROJETOS DO GITHUB (Step 3):',
    avaliacao,
    '',
    'Reconstrua o currículo completo e retorne APENAS este JSON:',
    '{',
    '  "nome": "<nome completo>",',
    '  "titulo_profissional": "<cargo ou área de atuação>",',
    '  "contato": {',
    '    "email": "<email ou vazio>",',
    '    "telefone": "<telefone ou vazio>",',
    '    "linkedin": "<url linkedin ou vazio>",',
    '    "github": "<url github ou vazio>",',
    '    "cidade": "<cidade, estado ou vazio>",',
    '    "portfolio": "<url portfolio ou vazio>"',
    '  },',
    '  "resumo_profissional": "<2-3 frases de impacto sobre o profissional>",',
    '  "experiencias": [',
    '    {',
    '      "empresa": "<nome da empresa>",',
    '      "cargo": "<cargo>",',
    '      "periodo": "<Mês Ano – Mês Ano ou Atual>",',
    '      "local": "<cidade ou Remoto>",',
    '      "bullets": ["<realizacao com verbo de acao e metrica>", "<bullet 2>"]',
    '    }',
    '  ],',
    '  "projetos": [',
    '    {',
    '      "nome": "<nome do projeto>",',
    '      "tecnologias": "<stack principal>",',
    '      "descricao": "<1-2 frases de impacto>",',
    '      "url": "<link github/demo ou vazio>"',
    '    }',
    '  ],',
    '  "formacao": [',
    '    {',
    '      "instituicao": "<nome>",',
    '      "curso": "<nome do curso>",',
    '      "periodo": "<Ano – Ano ou Cursando>"',
    '    }',
    '  ],',
    '  "habilidades_tecnicas": ["<skill1>", "<skill2>"],',
    '  "habilidades_interpessoais": ["<soft skill>"],',
    '  "idiomas": [',
    '    { "idioma": "<nome>", "nivel": "<Básico | Intermediário | Avançado | Fluente | Nativo>" }',
    '  ],',
    '  "certificacoes": ["<nome do curso/certificação (plataforma, ano)>"]',
    '}',
    '',
    'Regras CRÍTICAS:',
    '- LIMITE DE ESPAÇO: o currículo deve caber em no máximo 2 páginas. Seja conciso.',
    '- Substitua projetos fracos pelos melhores projetos do GitHub identificados no step3.',
    '- Reescreva todos os bullets de experiência com verbos de ação e métricas reais quando possível.',
    '- Adicione as skills_descobertas do step3 em habilidades_tecnicas se ainda não estiverem.',
    '- Preserve TODAS as informações reais do currículo original (empresa, datas, formação).',
    '- Não invente experiências, empresas ou cursos que não existem no original.',
    '- Se uma seção não existir no currículo original, deixe o array vazio [].',
    '- resumo_profissional: escreva baseado na experiência real, não genérico.',
    '- bullets: entre 2 e 4 por experiência, focados em impacto mensurável.',
  ].join('\n')
}
